using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> AfricanGenres = new()
        {
            "african heavy metal",
            "african hip hop",
            "african popular music",
            "african",
            "afro house",
            "afro pop",
            "afro-soul",
            "afrobeat",
            "afrobeats",
            "afropop",
            "amapiano",
            "apala",
            "arabesque",
            "azonto",
            "batuque",
            "benga",
            "bikutsi",
            "bongo flava",
            "boomba",
            "cape jazz",
            "chaabi",
            "chalga",
            "chaoui music",
            "chimurenga",
            "coco",
            "coladeira",
            "congolese rumba",
            "coupé-décalé",
            "fuji music",
            "funaná",
            "genge",
            "gengeton",
            "ghana",
            "gnawa",
            "gqom",
            "highlife",
            "hipco",
            "hiplife",
            "igbo highlife",
            "igbo rap",
            "isicathamiya",
            "jit",
            "jùjú",
            "kadongo kamu",
            "kalindula",
            "kaseko",
            "kaséko",
            "kilalaky",
            "kizomba",
            "kuduro",
            "kwaito",
            "kwassa kwassa",
            "kwela",
            "ma'luf",
            "makossa",
            "maloya",
            "marabi",
            "marrabenta",
            "mbalax",
            "mbaqanga",
            "mbube",
            "morna",
            "museve",
            "ndombolo",
            "ogene",
            "palm-wine",
            "pandza",
            "qaraami",
            "raï",
            "sakara",
            "salegy",
            "sega",
            "séga",
            "seggae",
            "semba",
            "shangaan electro",
            "soukous",
            "sudanese popular music",
            "sungura",
            "taarab",
            "zamrock",
            "zimbabwean",
            "zouglou"
        };
    }
}
