using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> AsianGenres = new()
        {
            "akishibu-kei",
            "anime music",
            "anime song",
            "anime",
            "asian underground",
            "asian",
            "baila",
            "baul",
            "beiguan music",
            "bhangra",
            "bhawaiya",
            "bushi",
            "c-pop",
            "cantopop",
            "carnatic classical",
            "carnatic",
            "chinese folk music",
            "chinese heavy metal",
            "chinese hip hop",
            "chinese revolutionary opera",
            "chinese rock",
            "city pop",
            "dangdut",
            "danmono",
            "denpa song",
            "denpa",
            "dohori",
            "dongjing",
            "enka",
            "esashi oiwake music",
            "eurobeat",
            "filmi",
            "footwork",
            "gagaku",
            "gamelan",
            "gangtai",
            "gigaku",
            "group sounds",
            "guangdong music",
            "guoyue",
            "hindustani classical",
            "hokkien pop",
            "hong kong english pop",
            "hong kong hip hop",
            "hong kong musical tongue twister",
            "honkyoku",
            "indian classical",
            "indian jazz",
            "indian pop",
            "indian rock",
            "indo pop",
            "indorock",
            "j-pop",
            "j-punk",
            "j-rock",
            "j-ska",
            "j-synth",
            "jaipongan",
            "japan",
            "japanese hardcore",
            "japanese hip hop",
            "japanese jazz",
            "japanese metal",
            "japanese reggae",
            "japanese rock",
            "japanese ska",
            "japanoise",
            "jiangnan sizhu",
            "jōruri",
            "jpop",
            "k-pop",
            "kawaii metal",
            "kawaii",
            "kayōkyoku",
            "keroncong",
            "korean folk music",
            "korean hip hop",
            "korean revolutionary opera",
            "korean rock",
            "kpop",
            "kuthu",
            "l-pop",
            "lavani",
            "luk krung",
            "luk thung",
            "luogu",
            "malaysian hip hop",
            "malaysian pop",
            "malaysian rock",
            "mandopop",
            "manila sound",
            "meriyasu",
            "mor lam",
            "morlam",
            "nagauta",
            "nagoya kei",
            "nanguan music",
            "nōgaku",
            "noh",
            "northwest wind",
            "nyu myujikku",
            "ondo",
            "onkyo",
            "onkyokei",
            "original pilipino",
            "pinoy pop",
            "pinoy rock",
            "quyi",
            "raga rock",
            "ragini",
            "rōkyoku",
            "ryukoka",
            "ryūkōka",
            "shibuya-kei",
            "shidaiqu",
            "shōmyō",
            "sufi rock",
            "suizen",
            "sundanese pop",
            "taiwanese hip hop",
            "taiwanese pop",
            "taiwanese rock",
            "taoist music",
            "teochew string music",
            "thai pop",
            "thai string pop",
            "tokyo",
            "tomimoto-bushi",
            "touhou",
            "trot",
            "tsugaru-jamisen",
            "v-pop",
            "visual kei",
            "wuxi opera",
            "yōkyoku",
            "zhongguo feng",
        };
    }
}
