using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> AvantGardeOrExeprimentalGenres = new()
        {
            "aleatoric music",
            "alternative hip hop",
            "art pop",
            "art punk",
            "art rock",
            "avant garde",
            "avant-folk",
            "avant-funk",
            "avant-garde jazz",
            "avant-garde metal",
            "avant-garde pop",
            "avant-garde",
            "avant-pop",
            "avant-prog",
            "avant-punk",
            "avantgarde",
            "breakcore",
            "danger music",
            "electroacoustic",
            "electronic music",
            "experimental hip hop",
            "experimental pop",
            "experimental rock",
            "experimental",
            "free folk",
            "free improvisation",
            "free jazz",
            "glitch",
            "indeterminacy in music",
            "industrial music",
            "lo-fi hip hop",
            "lo-fi",
            "lowercase music",
            "math rock",
            "microsound",
            "microtonal",
            "microtonality",
            "minimal",
            "minimalism"
            "musique concrète",
            "no wave",
            "noise music",
            "noise pop",
            "noise rock",
            "noise",
            "non-music",
            "onkyo",
            "outsider music",
            "post-hardcore",
            "post-progressive",
            "post-punk",
            "post-rock",
            "progressive music",
            "progressive pop",
            "progressive rock",
            "progressive",
            "sound art",
            "spectralism",
            "surrealist music",
            "zolo",
        };
    }
}
