using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> BluesGenres = new()
        {
            "acoustic blues",
            "african blues",
            "anatolian blues",
            "beat music",
            "blues ballad",
            "blues rock",
            "blues shouter",
            "blues",
            "boogie-woogie",
            "boogie",
            "british blues",
            "canadian blues",
            "chicago blues festival",
            "chicago blues",
            "classic blues",
            "classic female blues",
            "contemporary r&b",
            "country blues",
            "delta blues",
            "desert blues",
            "detroit blues",
            "dirty blues",
            "doo-wop",
            "electric blues",
            "fife and drum blues",
            "gospel blues",
            "harmonica blues",
            "hill country blues",
            "hokum blues",
            "hokum",
            "holler blues",
            "indian blues",
            "jug band",
            "jump blues",
            "kansas city blues",
            "louisiana blues",
            "maxwell street",
            "memphis blues",
            "modern blues",
            "music of chicago",
            "new blues",
            "new orleans blues",
            "new orleans rhythm and blues",
            "piano blues",
            "piedmont blues",
            "punk blues",
            "rhythm and blues",
            "skiffle",
            "slide guitar",
            "soul blues",
            "st. louis blues",
            "swamp blues",
            "texas blues",
            "twelve-bar blues",
            "west coast blues"
        };
    }
}
