using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> ClassicalGenres = new()
        {
            "allemande",
            "andalusian classical music",
            "arabesque",
            "ars antiqua",
            "ars nova",
            "ars subtilior",
            "bagatelle",
            "ballad opera",
            "ballade",
            "ballata",
            "ballet",
            "baroque music",
            "baroque",
            "bassoon sonata",
            "big band",
            "burlesque",
            "cabaret",
            "canon",
            "cantata",
            "cantus firmus mass",
            "canzona",
            "caprice",
            "carnatic classical",
            "carol",
            "cello concerto",
            "cello sonata",
            "chaconne",
            "chamber music",
            "chanson a texte",
            "chanson",
            "choral symphony",
            "chromatic fantasia",
            "clarinet concerto",
            "clarinet sonata",
            "classical ballet",
            "classical period",
            "classical",
            "concert aria",
            "concert overture",
            "concerto for orchestra",
            "concerto grosso",
            "concerto",
            "contemporary ballet",
            "contemporary classical music",
            "contemporary classical",
            "courante",
            "cyclic mass",
            "dance",
            "divertimento",
            "double bass concerto",
            "early music",
            "electronic music",
            "estampie",
            "étude",
            "experimental music theatre",
            "experimental music",
            "fantasia",
            "fantasy",
            "film score",
            "flute concerto",
            "flute sonata",
            "fugue",
            "galant music",
            "galliard",
            "gavotte",
            "gigue",
            "gregorian chant",
            "high modernism",
            "impressionism",
            "impromptu",
            "indian classical music",
            "intermedio",
            "intermezzo",
            "jaipongan",
            "korean court music",
            "lauda",
            "lied",
            "litany",
            "madrigal comedy",
            "madrigal",
            "madrigale spirituale",
            "march",
            "mass",
            "mazurka",
            "medieval music",
            "medieval",
            "minimal music",
            "minuet",
            "modern classical",
            "modernism",
            "moment form",
            "motet-chanson",
            "motet",
            "music hall",
            "musical theatre",
            "neo-classical",
            "neoclassical ballet",
            "neoclassical",
            "neoclassicism",
            "nocturne",
            "oboe concerto",
            "oboe quartet",
            "octet",
            "opera buffa",
            "opéra comique",
            "opera seria",
            "opera",
            "operetta",
            "oratorio",
            "orchestral",
            "organum",
            "overture",
            "paraphrase mass",
            "parody mass",
            "partita",
            "passacaglia",
            "passepied",
            "pastorale",
            "pavane",
            "persian classical music",
            "piano concerto",
            "piano quartet",
            "piano quintet",
            "piano sonata",
            "polonaise",
            "post-classical",
            "post-minimalism",
            "postmodern music",
            "prelude",
            "program symphony",
            "quartet",
            "quintet",
            "renaissance music",
            "renaissance",
            "requiem",
            "rhapsody",
            "ricercar",
            "romantic classical",
            "romantic music",
            "rondo",
            "saltarello",
            "sarabande",
            "scherzo",
            "score",
            "sequence",
            "serenade",
            "sinfonia concertante",
            "sinfonia",
            "singspiel",
            "slow waltz",
            "solo concerto",
            "sonata",
            "sonatina",
            "song cycle",
            "soundtrack",
            "string quartet",
            "string quintet",
            "suite",
            "symphonic poem",
            "symphony",
            "tiento",
            "toccata",
            "traditional music",
            "traditional",
            "trio sonata",
            "trio",
            "trumpet concerto",
            "vaudeville",
            "viola concerto",
            "viola sonata",
            "violin concerto",
            "violin sonata",
            "waltz",
            "western classical music",
            "wind quintet",
            "zarzuela",
        };
    }
}
