using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> ClassicalGenres = new()
        {
            "allemande",
            "andalusian classical music",
            "arabesque",
            "ars antiqua",
            "ars nova",
            "ars subtilior",
            "bagatelle",
            "ballad opera",
            "ballade",
            "ballata",
            "ballet",
            "baroque",
            "baroque music",
            "bassoon sonata",
            "big band",
            "burlesque",
            "cabaret",
            "canon",
            "cantata",
            "cantus firmus mass",
            "canzona",
            "caprice",
            "carnatic classical",
            "carol",
            "cello concerto",
            "cello sonata",
            "chaconne",
            "chanson",
            "chanson a texte",
            "choral symphony",
            "chromatic fantasia",
            "clarinet concerto",
            "clarinet sonata",
            "classical",
            "classical ballet",
            "classical period",
            "concert aria",
            "concert overture",
            "concerto",
            "concerto for orchestra",
            "concerto grosso",
            "contemporary ballet",
            "contemporary classical",
            "contemporary classical music",
            "courante",
            "cyclic mass",
            "dance",
            "divertimento",
            "double bass concerto",
            "early music",
            "electronic music",
            "estampie",
            "experimental music",
            "experimental music theatre",
            "fantasia",
            "fantasy",
            "film score",
            "flute concerto",
            "flute sonata",
            "fugue",
            "galant music",
            "galliard",
            "gavotte",
            "gigue",
            "gregorian chant",
            "high modernism",
            "impressionism",
            "impromptu",
            "indian classical music",
            "intermedio",
            "intermezzo",
            "jaipongan",
            "korean court music",
            "lauda",
            "lied",
            "litany",
            "madrigal",
            "madrigal comedy",
            "madrigale spirituale",
            "march",
            "mass",
            "mazurka",
            "medieval",
            "medieval music",
            "minimal music",
            "minuet",
            "modern classical",
            "modernism",
            "moment form",
            "motet",
            "motet-chanson",
            "music hall",
            "musical theatre",
            "neoclassical ballet",
            "neoclassicism",
            "nocturne",
            "oboe concerto",
            "oboe quartet",
            "octet",
            "opera",
            "opera buffa",
            "opera seria",
            "operetta",
            "opéra comique",
            "oratorio",
            "orchestral",
            "organum",
            "overture",
            "paraphrase mass",
            "parody mass",
            "partita",
            "passacaglia",
            "passepied",
            "pastorale",
            "pavane",
            "persian classical music",
            "piano concerto",
            "piano quartet",
            "piano quintet",
            "piano sonata",
            "polonaise",
            "post-classical",
            "post-minimalism",
            "postmodern music",
            "prelude",
            "program symphony",
            "quartet",
            "quintet",
            "renaissance",
            "renaissance music",
            "requiem",
            "rhapsody",
            "ricercar",
            "romantic classical",
            "romantic music",
            "rondo",
            "saltarello",
            "sarabande",
            "scherzo",
            "sequence",
            "serenade",
            "sinfonia",
            "sinfonia concertante",
            "singspiel",
            "slow waltz",
            "solo concerto",
            "sonata",
            "sonatina",
            "song cycle",
            "soundtrack",
            "string quartet",
            "string quintet",
            "suite",
            "symphonic poem",
            "symphony",
            "tiento",
            "toccata",
            "trio",
            "trio sonata",
            "trumpet concerto",
            "vaudeville",
            "viola concerto",
            "viola sonata",
            "violin concerto",
            "violin sonata",
            "waltz",
            "western classical music",
            "wind quintet",
            "zarzuela",
            "étude"
        };
    }
}
