using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> CountryGenres = new()
        {
            "alternative country",
            "americana",
            "appalachian bluegrass",
            "australian country music",
            "australian country",
            "bakersfield sound",
            "beijing opera",
            "bluegrass gospel",
            "bluegrass",
            "bro-country",
            "bush band",
            "cajun fiddle",
            "cajun",
            "canadian country music",
            "christian country music",
            "christian country",
            "classic country",
            "close harmony",
            "contemporary country",
            "cosmopolitan country",
            "country and irish",
            "country blues",
            "country boogie",
            "country edm",
            "country en español",
            "country folk",
            "country pop",
            "country rap",
            "country rock",
            "country soul",
            "country-punk",
            "country",
            "countrypolitan",
            "cowboy pop",
            "cowboy",
            "cowpunk",
            "dansband music",
            "dansband",
            "franco-country",
            "gothabilly",
            "gothic country",
            "gulf and western",
            "hellbilly",
            "hick-hop",
            "hokum",
            "honky tonk music",
            "honky tonk",
            "instrumental country",
            "lubbock sound",
            "modern country",
            "nashville sound",
            "neo-rockabilly",
            "neo-traditional bluegrass",
            "neo-traditional country",
            "neotraditional country",
            "new country",
            "new mexico music",
            "new mexico",
            "nu-grass",
            "old-time bluegrass",
            "old-time music",
            "outlaw country",
            "progressive bluegrass",
            "progressive country",
            "psychobilly",
            "punkabilly",
            "reactionary bluegrass",
            "red dirt",
            "rockabilly",
            "roots rock",
            "sertanejo",
            "southern rock",
            "southern soul",
            "talking blues",
            "tejano",
            "tex-mex",
            "texas country",
            "traditional bluegrass",
            "traditional country music",
            "traditional country",
            "truck-driving country",
            "urban cowboy",
            "western music",
            "western swing",
            "zydeco"
        };
    }
}
