using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> CountryGenres = new()
        {
            "alternative country",
            "americana",
            "appalachian bluegrass",
            "australian country",
            "australian country music",
            "bakersfield sound",
            "beijing opera",
            "bluegrass",
            "bluegrass gospel",
            "bro-country",
            "bush band",
            "cajun",
            "cajun fiddle",
            "canadian country music",
            "christian country",
            "christian country music",
            "classic country",
            "close harmony",
            "contemporary country",
            "cosmopolitan country",
            "country",
            "country and irish",
            "country blues",
            "country boogie",
            "country edm",
            "country en español",
            "country folk",
            "country pop",
            "country rap",
            "country rock",
            "country soul",
            "country-punk",
            "countrypolitan",
            "cowboy",
            "cowboy pop",
            "cowpunk",
            "dansband",
            "dansband music",
            "franco-country",
            "gothabilly",
            "gothic country",
            "gulf and western",
            "hellbilly",
            "hick-hop",
            "hokum",
            "honky tonk",
            "honky tonk music",
            "instrumental country",
            "lubbock sound",
            "modern country",
            "nashville sound",
            "neo-rockabilly",
            "neo-traditional bluegrass",
            "neo-traditional country",
            "neotraditional country",
            "new country",
            "new mexico",
            "new mexico music",
            "nu-grass",
            "old-time bluegrass",
            "old-time music",
            "outlaw country",
            "progressive bluegrass",
            "progressive country",
            "psychobilly",
            "punkabilly",
            "reactionary bluegrass",
            "red dirt",
            "rockabilly",
            "roots rock",
            "sertanejo",
            "southern rock",
            "southern soul",
            "talking blues",
            "tejano",
            "tex-mex",
            "texas country",
            "traditional bluegrass",
            "traditional country",
            "traditional country music",
            "truck-driving country",
            "urban cowboy",
            "western music",
            "western swing",
            "zydeco"
        };
    }
}
