using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> ElectronicGenres = new()
        {
            "2-step",
            "2-step garage",
            "4-beat",
            "acid breaks",
            "acid house",
            "acid jazz",
            "acid techno",
            "acid trance",
            "acidcore",
            "acousmatic music",
            "african electronic dance music",
            "afro house",
            "afro trap",
            "afro/cosmic music",
            "afrobeats",
            "afroswing",
            "aggrotech",
            "algorave",
            "alternative dance",
            "alternative hip hop",
            "amapiano",
            "ambient",
            "ambient dub",
            "ambient house",
            "ambient industrial",
            "ambient techno",
            "andean new-age",
            "artcore",
            "asian underground",
            "atmospheric drum and bass",
            "azonto",
            "baggy",
            "balearic beat",
            "balearic trance",
            "ballroom",
            "baltimore club",
            "bass house",
            "bass music",
            "bassline",
            "berlin school",
            "berlin techno",
            "big beat",
            "big room house",
            "birmingham sound",
            "bitpop",
            "bleep techno",
            "blog house",
            "boogie",
            "bouncy techno",
            "brazilian bass",
            "breakbeat",
            "breakbeat hardcore",
            "breakcore",
            "breaks",
            "breakstep",
            "broken beat",
            "brooklyn drill",
            "brostep",
            "bubblegum bass",
            "budots",
            "bytebeat",
            "changa tuki",
            "chicago hard house",
            "chicago house",
            "chill-out",
            "chillstep",
            "chillsynth",
            "chillwave",
            "chiptune",
            "chopped and screwed",
            "city pop",
            "cloud rap",
            "clownstep",
            "club",
            "cold wave",
            "complextro",
            "coupé-décalé",
            "crunk",
            "crunkcore",
            "cyber metal",
            "cyberpunk",
            "dance-pop",
            "dance-punk",
            "dance-rock",
            "dancehall pop",
            "danger music",
            "dark ambient",
            "dark electro",
            "dark psytrance",
            "dark wave",
            "darkcore",
            "darkstep",
            "darksynth",
            "death industrial",
            "deathstep",
            "deconstructed club",
            "deep house",
            "deep techno",
            "detroit techno",
            "digital hardcore",
            "disco",
            "disco edits",
            "disco house",
            "disco polo",
            "diva house",
            "doomcore",
            "downtempo",
            "dream trance",
            "dreampunk",
            "drill",
            "drill 'n' bass",
            "drill and bass",
            "drone",
            "drum and bass",
            "drum'n'core",
            "drumfunk",
            "drumstep",
            "dub",
            "dub poetry",
            "dub techno",
            "dubstep",
            "dubstyle",
            "dubtronica",
            "dungeon synth",
            "dutch house",
            "early hardcore",
            "ebm",
            "edm",
            "electro",
            "electro house",
            "electro swing",
            "electro-disco",
            "electro-funk",
            "electro-industrial",
            "electroacoustic improvisation",
            "electroacoustic music",
            "electroclash",
            "electrogrind",
            "electronic",
            "electronic body music",
            "electronic rock",
            "electronica",
            "electronicore",
            "electropop",
            "electropunk",
            "electrotango",
            "emo rap",
            "ethereal wave",
            "ethnic electronica",
            "euphoric frenchcore",
            "euphoric hardstyle",
            "euro house",
            "eurobeat",
            "eurodance",
            "eurodisco",
            "eurohouse",
            "eurotrance",
            "extratone",
            "fidget house",
            "flashcore",
            "florida breaks",
            "fm synthesis",
            "folktronica",
            "footwork",
            "free tekno",
            "freeform hardcore",
            "french house",
            "frenchcore",
            "full-on",
            "funk carioca",
            "funk fusion genres",
            "funk ostentação",
            "funkot",
            "funkstep",
            "funktronica",
            "funky house",
            "future bass",
            "future funk",
            "future garage",
            "future house",
            "futurepop",
            "gabber",
            "gabber metal",
            "garage house",
            "ghetto house",
            "ghettotech",
            "glitch",
            "glitch hop",
            "glitch pop",
            "goa trance",
            "gorenoise",
            "gqom",
            "grime",
            "grindie",
            "hands up",
            "happy hardcore",
            "hard house",
            "hard nrg",
            "hard trance",
            "hardbag",
            "hardbass",
            "hardcore",
            "hardcore breaks",
            "hardcore techno",
            "hardstep",
            "hardstyle",
            "hardtechno",
            "hardvapour",
            "hardwave",
            "harsh noise",
            "harsh noise wall",
            "hauntology",
            "hi-nrg",
            "house",
            "house music",
            "hyperpop",
            "hypertone",
            "hypnagogic pop",
            "idm",
            "illbient",
            "indietronica",
            "industrial",
            "industrial hardcore",
            "industrial hip hop",
            "industrial metal",
            "industrial musical",
            "industrial rock",
            "industrial techno",
            "instrumental hip hop",
            "intelligent dance music",
            "intelligent drum and bass",
            "isolationism",
            "italo dance",
            "italo disco",
            "italo house",
            "italo-disco",
            "j-core",
            "japanoise",
            "jazz house",
            "jazzstep",
            "jazztronica",
            "jersey club",
            "juke",
            "juke house",
            "jump-up",
            "jumpstyle",
            "jungle",
            "jungle terror",
            "jungletek",
            "kawaii future bass",
            "kidandali",
            "kosmische musik",
            "krautrock",
            "kuduro",
            "kwaito",
            "laptronica",
            "latin freestyle",
            "latin house",
            "latin trap",
            "leftfield",
            "lento violento",
            "liquid funk",
            "live electronics",
            "livetronica",
            "lofi hip hop",
            "lolicore",
            "lowercase",
            "madchester",
            "mahraganat",
            "mainstream hardcore",
            "mallsoft",
            "manila sound",
            "martial industrial",
            "melbourne bounce",
            "melodic dubstep",
            "melodic funk",
            "melodic house",
            "melodic techno",
            "melodic trance",
            "merenhouse",
            "miami bass",
            "microhouse",
            "midtempo bass",
            "minimal drum and bass",
            "minimal psytrance",
            "minimal techno",
            "minimal wave",
            "moombahcore",
            "moombahsoul",
            "moombahton",
            "mumble rap",
            "musique concrète",
            "mákina",
            "neo soul",
            "neo trance",
            "neoclassical dark wave",
            "neoclassical new-age",
            "neue deutsche härte",
            "neue deutsche todeskunst",
            "neue deutsche welle",
            "neurofunk",
            "neurohop",
            "new beat",
            "new jersey sound",
            "new rave",
            "new romantic",
            "new wave",
            "new-age",
            "nightcore",
            "nintendocore",
            "nitzhonot",
            "noise music",
            "noisecore",
            "nortec",
            "nu skool breaks",
            "nu-disco",
            "nu-gaze",
            "onkyokei",
            "outsider house",
            "peak time techno",
            "philly club",
            "phonk",
            "plunderphonics",
            "poky",
            "post-disco",
            "post-dubstep",
            "post-rock",
            "power electronics",
            "power noise",
            "progressive breaks",
            "progressive electronic",
            "progressive house",
            "progressive psytrance",
            "progressive trance",
            "proibidão",
            "psybient",
            "psychedelic breakbea",
            "psychedelic breakbeat",
            "psychedelic trance",
            "psydub",
            "psytrance",
            "pumping house",
            "rabòday",
            "ragga jungle",
            "raggacore",
            "raggatek",
            "rara tech",
            "rasteirinha",
            "rave",
            "rawstyle",
            "reductionism",
            "reggaestep",
            "regional edm",
            "rhythmic noise",
            "riddim",
            "russ music",
            "sambass",
            "sampledelia",
            "schaffel",
            "schranz",
            "scouse house",
            "sequencer music",
            "shamstep",
            "shangaan electro",
            "skullstep",
            "skweee",
            "slap house",
            "snap music",
            "sophisti-pop",
            "soulful house",
            "soundscape",
            "sovietwave",
            "space disco",
            "space music",
            "space rock",
            "spacesynth",
            "speed garage",
            "speedbass",
            "speedcore",
            "splittercore",
            "suomisaundi",
            "synth funk",
            "synth-funk",
            "synth-metal",
            "synth-pop",
            "synth-punk",
            "synthwave",
            "tech house",
            "tech trance",
            "techno",
            "techno bass",
            "techno kayo",
            "technoid",
            "techstep",
            "tecno brega",
            "terrorcore",
            "toytown techno",
            "trance",
            "trance music",
            "trancecore",
            "trancestep",
            "trap",
            "trap edm",
            "trapstyle",
            "tribal guarachero",
            "tribal house",
            "tribe",
            "trip hop",
            "trip rock",
            "tropical house",
            "uk bass",
            "uk drill",
            "uk funky",
            "uk garage",
            "uk hard house",
            "uk hardcore",
            "uk trap",
            "uplifting trance",
            "vaporwave",
            "video game music",
            "vocal house",
            "vocal trance",
            "wave",
            "witch house",
            "wonky",
            "wonky techno",
            "worldbeat",
            "zenonesque"
        };
    }
}
