using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> FolkGenres = new()
        {
            "alternative folk",
            "american folk revival",
            "americana",
            "anti-folk",
            "appalachian folk",
            "arabesque",
            "arapaho music",
            "avant-folk",
            "ballad",
            "barbershop",
            "bardcore",
            "boeremusiek",
            "british folk revival",
            "campus folk",
            "canzone napoletana",
            "cape breton fiddling",
            "carimbó",
            "cariso",
            "celtic music",
            "celtic rock",
            "celtic",
            "chacarera",
            "chalga",
            "chamamé",
            "chanson a texte",
            "chutney music",
            "chutney parang",
            "chutney soca",
            "contemporary christian",
            "contemporary folk",
            "contra",
            "corrido",
            "country folk",
            "dangdut",
            "dark folk",
            "dene music",
            "ethnic electronica",
            "filk music",
            "filk",
            "folk baroque",
            "folk jazz",
            "folk music",
            "folk rock",
            "folk-pop",
            "folk",
            "folktronica",
            "freak folk",
            "free folk",
            "indie folk",
            "industrial folk music",
            "industrial folk",
            "irish folk",
            "joik",
            "kaiso",
            "klezmer",
            "koplo",
            "kwakwaka",
            "neofolk",
            "spoken word"
        };
    }
}
