using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> HipHopGenres = new()
        {
            "alternative hip hop",
            "battle rap",
            "boom bap",
            "bounce",
            "british hip hop",
            "brooklyn drill",
            "chap hop",
            "chicano rap",
            "chopped and screwed",
            "chopper",
            "christian hip hop",
            "cloud rap",
            "comedy hip hop",
            "conscious hip hop",
            "country rap",
            "crunk",
            "crunkcore",
            "dirty rap",
            "drill",
            "drill music",
            "east coast hip hop",
            "emo rap",
            "experimental hip hop",
            "freestyle rap",
            "g-funk",
            "gangsta rap",
            "hardcore hip hop",
            "hexd",
            "hip hop",
            "hip hop soul",
            "hip-hop",
            "hipster hop",
            "horrorcore",
            "hyphy",
            "industrial hip hop",
            "instrumental hip hop",
            "jazz rap",
            "jerkin'",
            "jewish hip hop",
            "juke",
            "latin hip hop",
            "latin trap",
            "lo-fi hip hop",
            "lofi hip hop",
            "mafioso rap",
            "memphis rap",
            "miami bass",
            "mumble rap",
            "nerdcore",
            "new jack swing",
            "phonk",
            "plugg",
            "political hip hop",
            "pop rap",
            "progressive rap",
            "punk rap",
            "ragga hip hop",
            "ragga hip-hop",
            "rap metal",
            "rap opera",
            "rap rock",
            "rapcore",
            "religious hip hop",
            "road rap",
            "snap",
            "snap music",
            "southern hip hop",
            "trap",
            "trap metal",
            "trap music",
            "tread",
            "turntablism",
            "uk drill",
            "underground hip hop",
            "west coast hip hop",
        };
    }
}
