using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> IgnoredGenres = new()
        {
            "80s",
            "abstract",
            "acoustic",
            "alternative",
            "athens",
            "atlanta",
            "atmospheric",
            "austin",
            "australia",
            "barcelona",
            "bass",
            "beats",
            "belgium",
            "berlin",
            "boston",
            "bristol",
            "brooklyn",
            "california",
            "canada",
            "chicago",
            "christmas",
            "cinematic",
            "coldwave",
            "dark",
            "darkwave",
            "detroit",
            "devotional",
            "diy",
            "dreamwave",
            "drone ambient",
            "ethereal",
            "experiemental",
            "female vocals",
            "field recording",
            "field recordings",
            "finland",
            "florida",
            "france",
            "game",
            "garage",
            "german audiobook",
            "germany",
            "guitar",
            "heavy",
            "improvisation",
            "instrumental",
            "isrc",
            "italy",
            "live",
            "lofi",
            "london",
            "los angeles",
            "madrid",
            "manchester",
            "meditation music",
            "meditation",
            "melbourne",
            "melodic",
            "minneapolis",
            "montreal",
            "moscow",
            "music",
            "nashville",
            "netherlands",
            "new york",
            "new zealand",
            "no cover art",
            "oakland",
            "offizielle charts",
            "outrun",
            "paris",
            "philadelphia",
            "piano",
            "portland",
            "production music",
            "prog",
            "psych",
            "remix",
            "retro",
            "russia",
            "saint petersburg",
            "san francisco",
            "seattle",
            "singer-songwriter",
            "sound art",
            "space",
            "spain",
            "stockholm",
            "stoner",
            "sweden",
            "sydney",
            "synth",
            "synthesizer",
            "toronto",
            "tribal",
            "uk",
            "underground",
            "united kingdom",
            "united states",
            "vancouver",
            "vgm",
            "video game",
            "vocal",
            "washington",
            "western",
            "world music",
            "world",
        };
    }
}
