using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> JazzGenres = new()
        {
            "acid jazz",
            "afro-cuban jazz",
            "afrobeat",
            "alt-jazz",
            "avant-garde jazz",
            "balkan jazz",
            "bebop",
            "boogie-woogie",
            "bossa nova",
            "brazilian jazz",
            "british dance band",
            "cape jazz",
            "chamber jazz",
            "classic jazz",
            "contemporary jazz",
            "continental jazz",
            "cool jazz",
            "crossover jazz",
            "cubop",
            "dark jazz",
            "dixieland",
            "ethno jazz",
            "european free jazz",
            "experimental big band",
            "flamenco jazz",
            "folk jazz",
            "free funk",
            "free improvisation",
            "free jazz",
            "fusion",
            "future jazz",
            "gypsy jazz",
            "hard bop",
            "instrumental jazz",
            "jazz and blues",
            "jazz blues",
            "jazz fusion",
            "jazz mugham",
            "jazz rap",
            "jazz rock",
            "jazz-funk",
            "jazz",
            "kansas city jazz",
            "latin jazz",
            "list of jazz genres",
            "livetronica",
            "m-base",
            "mainstream jazz",
            "marabi",
            "modal jazz",
            "neo-bop jazz",
            "neo-swing",
            "new big band",
            "novelty ragtime",
            "nu jazz",
            "orchestral jazz",
            "post-bop",
            "progressive big band",
            "progressive jazz",
            "punk jazz",
            "ragtime",
            "roots/world/jazz/soul",
            "sacred jazz",
            "samba-jazz",
            "shibuya-kei",
            "ska jazz",
            "skiffle",
            "smooth jazz",
            "soul jazz",
            "straight-ahead jazz",
            "stride jazz",
            "stride",
            "swing music",
            "swing",
            "third stream",
            "trad jazz",
            "twelve-bar blues",
            "vocal jazz",
            "west coast jazz",
            "western swing",
            "yass"
        };
    }
}
