using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> LatinOrCarribeanGenres = new()
        {
            "abambucao",
            "abwe",
            "afro-cuban jazz",
            "afrosoca",
            "aguinaldo",
            "alegrías",
            "areito",
            "axé",
            "bachata",
            "bahamian rhyming spiritual",
            "baithak gana",
            "bakosó",
            "balada",
            "balakadri",
            "banda",
            "bashment soca",
            "batá and yuka",
            "batá-rumba",
            "bel air",
            "bembe",
            "berroche",
            "biguine",
            "biguine vidé",
            "bolero",
            "bolero son",
            "bomba",
            "boogaloo",
            "bossa nova",
            "bouyon",
            "bouyon gwada",
            "bouyon music",
            "brazilian rock",
            "brega",
            "brega funk",
            "brukdown",
            "bulerías",
            "bullerengue",
            "bèlè",
            "bélé",
            "cadence-lypso",
            "calipso",
            "calypso",
            "calypso jazz",
            "calypso music",
            "cantes de ida y vuelta",
            "carabiné",
            "caribbean pop",
            "carimbó",
            "cha-cha-chá",
            "chacarera",
            "chachachá",
            "chalupa",
            "chamamé",
            "champeta",
            "chandé",
            "changui",
            "charanga",
            "chicha",
            "choro",
            "chouval bwa",
            "chumba",
            "chut-kai-pang",
            "chutney",
            "chutney parang",
            "chutney soca",
            "chutney-soca",
            "columbia",
            "comparsa",
            "compas",
            "conga",
            "copla",
            "criolla",
            "cuban hip hop",
            "cuban jazz",
            "cubatón",
            "cumbia",
            "cumbia villera",
            "cumbión",
            "cuplé",
            "dancehall",
            "danza",
            "danzonete",
            "danzón",
            "dembow",
            "dengue",
            "descarga",
            "dominican rock",
            "dub",
            "décima",
            "electrotango",
            "extempo",
            "fandango",
            "fandangos",
            "fedu",
            "filín",
            "flamenco",
            "fling",
            "folk",
            "forró",
            "foxtrot",
            "frevo",
            "funk carioca",
            "gaga",
            "garabato",
            "garifuna music",
            "goombay",
            "gospelypso",
            "grito e' monte",
            "grupera",
            "guacherna",
            "guaguanco",
            "guajira",
            "guaracha",
            "guarapachangueo",
            "gwo ka",
            "habanera",
            "hip hop",
            "indo-caribbean",
            "iron band",
            "jalao",
            "jing-ping",
            "jump up",
            "junkanoo",
            "kadans",
            "kaiso",
            "kumina",
            "lambada",
            "latin",
            "latin alternative",
            "latin ballad",
            "latin christian",
            "latin hip hop",
            "latin house",
            "latin jazz",
            "latin pop",
            "latin rap",
            "latin rock",
            "latin soul",
            "latin trap",
            "lovers rock",
            "lumbalú",
            "mambo",
            "mangulina",
            "mapalé",
            "maracatu",
            "marchinha",
            "mariachi",
            "marimba",
            "martinetes",
            "matamuerte",
            "mazouk",
            "mazurka",
            "mento",
            "merecumbé",
            "merengue",
            "merengue house",
            "millo",
            "mini-jazz",
            "modeup",
            "mozambique",
            "mpb",
            "méringue",
            "música popular brasileira",
            "música sertaneja",
            "norteño",
            "nueva trova",
            "nuevo tango",
            "nyabinghi",
            "paca",
            "pachanga",
            "pagodao",
            "pagode",
            "palo music",
            "pambiche",
            "pan music",
            "parang",
            "parrandín",
            "paseaito",
            "paseo",
            "pasillo isleño",
            "perico ripiao",
            "perillero",
            "peteneras",
            "pichakaree",
            "pilón",
            "piqueria",
            "plena",
            "polka",
            "pop latino",
            "porro",
            "power soca",
            "praise hymn",
            "pregón",
            "punta",
            "punta rock",
            "punto guajiro",
            "puya",
            "quadrille",
            "ragga",
            "ragga hip-hop",
            "ragga jungle",
            "ragga soca",
            "rake-and-scrape",
            "ranchera",
            "rapso",
            "rasin",
            "reggae",
            "reggae en español",
            "reggae fusion",
            "reggae rock",
            "reggae-pop",
            "reggaeton",
            "regional mexican",
            "ritmo kombiná",
            "rock",
            "rock en español",
            "rocksteady",
            "romanza vallenata",
            "roots reggae",
            "rumba",
            "salsa",
            "salsa romántica",
            "salve",
            "samba",
            "samba rock",
            "samba-cançao",
            "samba-choro",
            "samba-exaltaçao",
            "samba-reggae",
            "samba-rock",
            "sarandunga",
            "schottis",
            "seis",
            "sertanejo raiz",
            "sertanejo romântico",
            "sertanejo universitário",
            "seú",
            "ska",
            "ska punk",
            "soca",
            "soca music",
            "socca",
            "soleá",
            "son",
            "son cubano",
            "son de negro",
            "son faroto",
            "son montuno",
            "son palenquero",
            "son sabanero",
            "son-batá",
            "songo",
            "spanish dancehall",
            "spouge",
            "tambora",
            "tambú",
            "tango",
            "tecnobrega",
            "tejano",
            "terapia",
            "timba",
            "toná",
            "tonás",
            "trapchata",
            "tropical",
            "tropicalia",
            "tropicália",
            "tropipop",
            "trova",
            "troval",
            "tuk",
            "tumba",
            "tumba francesa",
            "two-tone",
            "twoubadou",
            "upa",
            "vallenato",
            "vallenato y sus aires:",
            "vals isleño",
            "wals",
            "xote",
            "yahdees",
            "yambú",
            "yuca",
            "zafra",
            "zamba",
            "zapateo",
            "zarambo",
            "zouk",
            "zouk-lambada",
            "zumbi",
        };
    }
}
