using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> MetalGenres = new()
        {
            "alternative metal",
            "atmospheric black metal",
            "avant-garde metal",
            "avantgarde metal",
            "black metal",
            "blackened death metal",
            "blackgaze",
            "brutal death metal",
            "celtic metal",
            "christian metal",
            "crossover thrash",
            "death 'n' roll",
            "death metal",
            "death-doom",
            "death-doom metal",
            "deathcore",
            "deathgrind",
            "depressive black metal",
            "depressive suicidal black metal",
            "djent",
            "doom metal",
            "drone",
            "drone metal",
            "folk metal",
            "funeral doom metal",
            "funk metal",
            "glam metal",
            "goregrind",
            "gothic metal",
            "grindcore",
            "groove metal",
            "hair metal",
            "hardcore",
            "heavy metal",
            "industrial metal",
            "kawaii metal",
            "latin metal",
            "math metal",
            "mathcore",
            "medieval metal",
            "melodic black metal",
            "melodic death metal",
            "melodic metalcore",
            "metal",
            "metalcore",
            "modern metal",
            "national socialist black metal",
            "neoclassical metal",
            "neue deutsche härte",
            "new wave of british heavy metal",
            "nintendocore",
            "nu metal",
            "old school death metal",
            "pagan metal",
            "pirate metal",
            "pop metal",
            "porngrind",
            "post black metal",
            "post hardcore",
            "post metal",
            "post-metal",
            "power metal",
            "powerviolence",
            "progressive metal",
            "rap metal",
            "shitgrind",
            "slam death metal",
            "sludge",
            "sludge metal",
            "southern metal",
            "speed metal",
            "stoner doom metal",
            "stoner metal",
            "symphonic black metal",
            "symphonic metal",
            "technical death metal",
            "thrash metal",
            "true norwegian black metal",
            "unblack metal",
            "viking metal",
            "war metal",
            "mincecore"
        };
    }
}
