using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> MetalGenres = new()
        {
            "alternative metal",
            "atmospheric black metal",
            "avant-garde metal",
            "avantgarde metal",
            "black death metal",
            "black metal",
            "black-metal",
            "black/death-metal",
            "blackened death metal",
            "blackgaze",
            "blackmetal",
            "brutal death metal",
            "celtic metal",
            "chaotic hardcore",
            "christian metal",
            "classic metal",
            "crossover thrash",
            "dark metal",
            "death 'n' roll",
            "death doom metal",
            "death metal",
            "death thrash",
            "death-doom metal",
            "death-doom",
            "death-metal",
            "deathcore",
            "deathgrind",
            "deathmetal",
            "depressive black metal",
            "depressive suicidal black metal",
            "djent",
            "doom death metal",
            "doom metal",
            "doom",
            "drone metal",
            "drone",
            "epic black metal",
            "epic metal",
            "experimental black metal",
            "extreme metal",
            "folk metal",
            "funeral doom metal",
            "funk metal",
            "glam metal",
            "goregrind",
            "gothic metal",
            "grindcore",
            "groove metal",
            "hair metal",
            "hardcore",
            "heavy metal",
            "industrial metal",
            "kawaii metal",
            "latin metal",
            "math metal",
            "mathcore",
            "medieval metal",
            "melodic black metal",
            "melodic death metal",
            "melodic metal",
            "melodic metalcore",
            "metal",
            "metalcore",
            "mincecore",
            "modern metal",
            "national socialist black metal",
            "neoclassical metal",
            "neue deutsche härte",
            "new wave of british heavy metal",
            "nintendocore",
            "nu metal",
            "nu-metal",
            "old school death metal",
            "pagan black metal",
            "pagan metal",
            "pirate metal",
            "pop metal",
            "porngrind",
            "post black metal",
            "post hardcore",
            "post metal",
            "post-black metal",
            "post-metal",
            "power metal",
            "powerviolence",
            "progressive black metal",
            "progressive death metal",
            "progressive metal",
            "proto-metal",
            "rap metal",
            "raw black metal",
            "satan",
            "satanic",
            "shitgrind",
            "slam death metal",
            "slamming brutal death metal",
            "sludge metal",
            "sludge",
            "southern metal",
            "speed metal",
            "stoner doom metal",
            "stoner metal",
            "symphonic black metal",
            "symphonic metal",
            "technical death metal",
            "thrash metal",
            "thrash",
            "traditional heavy metal",
            "true norwegian black metal",
            "unblack metal",
            "viking metal",
            "war metal"
        };
    }
}
