using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> PopGenres = new()
        {
            "adult album alternative",
            "adult contemporary",
            "afropop",
            "alternative pop",
            "alternative pop/rock",
            "ambient pop",
            "arabic pop",
            "art pop",
            "austropop",
            "baroque pop",
            "bedroom pop",
            "brill building",
            "britpop",
            "bubblegum pop",
            "c-pop",
            "canción",
            "cantopop",
            "canzone",
            "chalga",
            "chamber pop",
            "chanson",
            "christian pop",
            "christmas music",
            "city pop",
            "classic hits",
            "classical crossover",
            "comedy",
            "contemporary christian",
            "contemporary pop/rock",
            "country pop",
            "cringe pop",
            "dance-pop",
            "disco polo",
            "electropop",
            "emo pop",
            "eurobeat",
            "europop",
            "fado",
            "folk pop",
            "french pop",
            "hokkien pop",
            "hyperpop",
            "indian pop",
            "indie pop",
            "iranian pop",
            "italo dance",
            "italo disco",
            "j-pop",
            "jangle pop",
            "jazz pop",
            "jpop",
            "k-pop",
            "korean hip hop",
            "korean rock",
            "kpop",
            "laïkó",
            "latin ballad",
            "latin pop",
            "line dance",
            "mandopop",
            "mexican pop",
            "musical",
            "nederpop",
            "neomelodic music",
            "neon pop",
            "new romantic",
            "oldies",
            "operatic pop",
            "opm",
            "pinoy pop",
            "pop punk",
            "pop rap",
            "pop rock",
            "pop soul",
            "pop yeh-yeh",
            "pop",
            "pop/rock",
            "pop/rock/indie/electronic",
            "power pop",
            "progressive pop",
            "psychedelic pop",
            "psychedelic",
            "rebetiko",
            "red song",
            "reggae-pop",
            "russian pop",
            "schlager",
            "shibuya-kei",
            "soft rock",
            "sophisti-pop",
            "space age pop",
            "sunshine pop",
            "surf pop",
            "swamp pop",
            "synth pop",
            "synthpop",
            "t'ong guitar",
            "teen pop",
            "traditional pop",
            "trot",
            "turbo-folk",
            "turkish pop",
            "twee pop",
            "vispop",
            "wonky pop",
            "worldbeat",
            "yacht rock",
            "yé-yé"
        };
    }
}
