using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> PunkGenres = new()
        {
            "2 tone",
            "afro-punk",
            "alternative punk",
            "anarcho punk",
            "anarcho-punk",
            "anti-folk",
            "art punk",
            "celtic punk",
            "chicano punk",
            "christian punk",
            "cowpunk",
            "crossover thrash",
            "crust punk",
            "crustgrind",
            "d-beat",
            "dance-punk",
            "dark cabaret",
            "deathrock",
            "digital hardcore",
            "easycore",
            "electropunk",
            "emo",
            "emo pop",
            "emocore",
            "folk punk",
            "garage punk",
            "glam punk",
            "goregrind",
            "gothic",
            "grindcore",
            "gypsy punk",
            "hardcore punk",
            "horror punk",
            "latin punk",
            "melodic hardcore",
            "melodic punk",
            "nazi punk",
            "neon pop",
            "noisegrind",
            "oi",
            "oi!",
            "peace punk",
            "pop punk",
            "pornogrind",
            "post-hardcore",
            "powerviolence",
            "proto-punk",
            "psychobilly",
            "punk",
            "punk blues",
            "punk jazz",
            "punk metal",
            "punk pathetique",
            "punk rock fusion subgenres",
            "queercore",
            "rapcore",
            "riot grrrl",
            "sasscore",
            "scottish gaelic punk",
            "screamo",
            "ska punk",
            "ska-core",
            "skacore",
            "skate punk",
            "spanish raw punk",
            "street punk",
            "synthpunk",
            "taqwacore",
            "thrashcore",
            "trallpunk"
        };
    }
}
