using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> RnBOrSoulGenres = new()
        {
            "acid jazz",
            "alternative r&b",
            "blue-eyed soul",
            "bluegrass gospel",
            "boogaloo",
            "boogie",
            "brown-eyed soul",
            "cinematic soul",
            "contemporary gospel",
            "contemporary r&b",
            "country soul",
            "deep funk",
            "deep soul",
            "disco",
            "doo wop",
            "doo-wop",
            "freestyle",
            "funk soul",
            "funk",
            "future soul",
            "go-go",
            "gospel music",
            "gospel",
            "hip hop soul",
            "jazz and blues",
            "latin soul",
            "minneapolis sound",
            "motown",
            "neo soul",
            "new jack swing",
            "northern soul",
            "p-funk",
            "philly soul",
            "porn groove",
            "post-disco",
            "progressive soul",
            "psychedelic funk",
            "psychedelic soul",
            "quiet storm",
            "r b",
            "r&b and soul",
            "r&b",
            "r&b/soul",
            "retro-soul",
            "rhythm and blues",
            "rnb",
            "roots/world/jazz/soul",
            "smooth soul",
            "soul blues",
            "soul jazz",
            "soul",
            "southern gospel",
            "southern soul",
            "west coast swing"
        };
    }
}
