using System.Collections.Generic;

namespace DataAcquisition.Shared.Genres
{
    public static partial class GenreAggregate
    {
        public static readonly HashSet<string> RockGenres = new()
        {
            "acid rock",
            "acoustic rock",
            "afro rock",
            "album rock",
            "alt rock",
            "alternative dance",
            "alternative pop/rock",
            "alternative rock",
            "alternative-rock",
            "alternative/indie rock",
            "aor",
            "arena rock",
            "art rock",
            "avant-prog",
            "baggy",
            "beat music",
            "beat",
            "blackgaze",
            "blues rock",
            "boogie rock",
            "british folk rock",
            "british invasion",
            "british rhythm and blues",
            "britpop",
            "canterbury scene",
            "celtic rock",
            "chamber pop",
            "christian rock",
            "classic rock",
            "cold wave",
            "comedy rock",
            "contemporary pop/rock",
            "country rock",
            "crossover prog",
            "dance-punk",
            "dark cabaret",
            "dark wave",
            "desert rock",
            "dream pop",
            "dreampop",
            "dunedin sound",
            "electronic rock",
            "electronicore",
            "emocore",
            "ethereal wave",
            "experimental rock",
            "flamenco rock",
            "folk rock",
            "freakbeat",
            "funk rock",
            "fusion",
            "garage rock",
            "general rock",
            "glam rock",
            "glam",
            "goth rock",
            "goth",
            "gothic rock",
            "gothic",
            "grebo",
            "grunge",
            "hard rock",
            "hardrock",
            "heartland rock",
            "heavy psych",
            "heavy rock",
            "indie rock",
            "indie",
            "indorock",
            "industrial rock",
            "instrumental rock",
            "jangle pop",
            "jazz fusion",
            "jazz rock",
            "krautrock",
            "latin rock",
            "madchester",
            "mainstream rock",
            "mangue bit",
            "math rock",
            "medieval folk rock",
            "melodic rock",
            "modern rock",
            "nagoya kei",
            "nederbeat",
            "neo-progressive rock",
            "neo-psychedelia",
            "new age",
            "new prog",
            "new wave",
            "no wave",
            "noise pop",
            "noise rock",
            "occult rock",
            "paisley underground",
            "piano rock",
            "pop rock",
            "pop/rock",
            "pop/rock/indie/electronic",
            "post rock",
            "post-britpop",
            "post-grunge",
            "post-progressive",
            "post-punk revival",
            "post-punk",
            "post-rock",
            "power pop",
            "prog rock",
            "progressive rock",
            "psychedelic rock",
            "pub rock",
            "punk rock",
            "raga rock",
            "rap rock",
            "rapcore",
            "reggae rock",
            "rock & roll",
            "rock and roll",
            "rock in opposition",
            "rock music",
            "rock n roll",
            "rock opera",
            "rock'n'roll",
            "rock",
            "rockabilly",
            "rocknroll",
            "roots rock",
            "sadcore",
            "shoegaze",
            "slowcore",
            "soft rock",
            "southern rock",
            "space rock",
            "stoner rock",
            "sufi rock",
            "surf rock",
            "swamp rock",
            "symphonic prog",
            "symphonic rock",
            "tropical rock",
            "visual kei",
            "wizard rock",
            "world fusion",
            "worldbeat",
            "yacht rock",
            "zolo"
        };
    }
}
